using WebExpress.WebCore.WebAttribute;
using WebExpress.WebCore.WebInclude;

namespace WebExpress.WebApp.WebInclude
{
    /// <summary>
    /// Represents a collection of JavaScript resources to be included in a 
    /// web application.
    /// </summary>
    /// <remarks>
    /// This class is used to define and manage the inclusion of JavaScript 
    /// files required for the functionality of a web application.
    /// </remarks>
    [Asset("/assets/js/webexpress.webapp.js")]
    [Asset("/assets/js/webexpress.webapp.service.js")]
    [Asset("/assets/js/webexpress.webapp.renderer.js")]
    [Asset("/assets/js/webexpress.webapp.template.js")]
    [Asset("/assets/js/webexpress.webapp.intent.js")]
    [Asset("/assets/js/webexpress.webapp.data.js")]
    [Asset("/assets/js/webexpress.webapp.viewstate.js")]
    [Asset("/assets/js/service/default.js")]
    [Asset("/assets/js/intent/default.js")]
    [Asset("/assets/js/bind/default.js")]
    [Asset("/assets/js/webexpress.webapp.avatar.dropdown.js")]
    [Asset("/assets/js/webexpress.webapp.chat.js")]
    [Asset("/assets/js/webexpress.webapp.collaborative.js")]
    [Asset("/assets/js/webexpress.webapp.comment.model.js")]
    [Asset("/assets/js/webexpress.webapp.comment.js")]
    [Asset("/assets/js/webexpress.webapp.comment.composer.model.js")]
    [Asset("/assets/js/webexpress.webapp.comment.composer.js")]
    [Asset("/assets/js/webexpress.webapp.dashboard.model.js")]
    [Asset("/assets/js/webexpress.webapp.dashboard.js")]
    [Asset("/assets/js/webexpress.webapp.dropdown.js")]
    [Asset("/assets/js/webexpress.webapp.dropdown.theme.model.js")]
    [Asset("/assets/js/webexpress.webapp.dropdown.theme.js")]
    [Asset("/assets/js/webexpress.webapp.gantt.model.js")]
    [Asset("/assets/js/webexpress.webapp.gantt.js")]
    [Asset("/assets/js/webexpress.webapp.input.cascading.js")]
    [Asset("/assets/js/webexpress.webapp.input.selection.model.js")]
    [Asset("/assets/js/webexpress.webapp.input.selection.js")]
    [Asset("/assets/js/webexpress.webapp.input.tile.js")]
    [Asset("/assets/js/webexpress.webapp.input.password.js")]
    [Asset("/assets/js/webexpress.webapp.input.unique.model.js")]
    [Asset("/assets/js/webexpress.webapp.input.unique.js")]
    [Asset("/assets/js/webexpress.webapp.kanban.model.js")]
    [Asset("/assets/js/webexpress.webapp.kanban.js")]
    [Asset("/assets/js/webexpress.webapp.list.model.js")]
    [Asset("/assets/js/webexpress.webapp.list.js")]
    [Asset("/assets/js/webexpress.webapp.login.js")]
    [Asset("/assets/js/webexpress.webapp.message.queue.status.js")]
    [Asset("/assets/js/webexpress.webapp.permission.model.js")]
    [Asset("/assets/js/webexpress.webapp.permission.js")]
    [Asset("/assets/js/webexpress.webapp.popupnotification.js")]
    [Asset("/assets/js/webexpress.webapp.progress.task.js")]
    [Asset("/assets/js/webexpress.webapp.status.task.js")]
    [Asset("/assets/js/webexpress.webapp.system.metric.js")]
    [Asset("/assets/js/webexpress.webapp.quickfilter.js")]
    [Asset("/assets/js/webexpress.webapp.restform.model.js")]
    [Asset("/assets/js/webexpress.webapp.restform.js")]
    [Asset("/assets/js/webexpress.webapp.restform.editor.js")]
    [Asset("/assets/js/webexpress.webapp.restwizard.model.js")]
    [Asset("/assets/js/webexpress.webapp.restwizard.js")]
    [Asset("/assets/js/webexpress.webapp.scrum.backlog.model.js")]
    [Asset("/assets/js/webexpress.webapp.scrum.backlog.js")]
    [Asset("/assets/js/webexpress.webapp.scrum.sprint.js")]
    [Asset("/assets/js/webexpress.webapp.scrum.team.model.js")]
    [Asset("/assets/js/webexpress.webapp.scrum.team.js")]
    [Asset("/assets/js/webexpress.webapp.scrum.velocity.model.js")]
    [Asset("/assets/js/webexpress.webapp.scrum.velocity.js")]
    [Asset("/assets/js/webexpress.webapp.search.js")]
    [Asset("/assets/js/webexpress.webapp.sidebar.model.js")]
    [Asset("/assets/js/webexpress.webapp.sidebar.js")]
    [Asset("/assets/js/webexpress.webapp.selection.model.js")]
    [Asset("/assets/js/webexpress.webapp.selection.js")]
    [Asset("/assets/js/webexpress.webapp.tab.model.js")]
    [Asset("/assets/js/webexpress.webapp.tab.js")]
    [Asset("/assets/js/webexpress.webapp.table.model.js")]
    [Asset("/assets/js/webexpress.webapp.table.js")]
    [Asset("/assets/js/webexpress.webapp.tag.js")]
    [Asset("/assets/js/webexpress.webapp.traffic.light.js")]
    [Asset("/assets/js/webexpress.webapp.tile.model.js")]
    [Asset("/assets/js/webexpress.webapp.tile.js")]
    [Asset("/assets/js/webexpress.webapp.watcher.model.js")]
    [Asset("/assets/js/webexpress.webapp.watcher.js")]
    [Asset("/assets/js/webexpress.webapp.workflow.editor.model.js")]
    [Asset("/assets/js/webexpress.webapp.workflow.editor.js")]
    [Asset("/assets/js/webexpress.webapp.wql.prompt.js")]
    [Asset("/assets/js/action/default.js")]
    [Asset("/assets/js/i18n/en.js")]
    [Asset("/assets/js/i18n/de.js")]
    [Asset("/assets/js/panels/webexpress.webapp.panel.workflow.guard.js")]
    [Asset("/assets/js/panels/webexpress.webapp.panel.workflow.postfunction.js")]
    [Asset("/assets/js/panels/webexpress.webapp.panel.workflow.state.properties.js")]
    [Asset("/assets/js/panels/webexpress.webapp.panel.workflow.transition.properties.js")]
    [Asset("/assets/js/panels/webexpress.webapp.panel.workflow.validator.js")]
    [Asset("/assets/js/syntax/wql.js")]
    [Asset("/assets/js/templates/default.js")]
    public sealed class IncludeJavaScript : IInclude
    {
    }
}
